services:
  # 1. The Database Service
  postgres:
    image: postgres:15-alpine
    container_name: bidify_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Database GUI (Optional, but recommended)
  pgadmin:
    image: dpage/pgadmin4
    container_name: bidify_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - postgres

  # Redis service
  redis:
    image: redis:alpine
    container_name: bidify_redis
    ports:
      - '6379:6379'
    restart: always

  rabbitmq:
    image: rabbitmq:4-management
    container_name: bidify_mq
    ports:
      - "5672:5672"   # For our Node app
      - "15672:15672" # For the Browser UI
    restart: always

  # Prometheus (The Collector)
  prometheus:
    image: prom/prometheus
    container_name: bidify_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  # Grafana (The Dashboard)
  grafana:
    image: grafana/grafana
    container_name: bidify_grafana
    ports:
      - "3001:3000" # Maps Grafana's 3000 to our 3001
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  postgres_data: